export const categorias = {

    TipoEntero : "TipoEntero",
    TipoDouble : "TipoReal",
    TipoString : "TipoCadena",
    PalabraReservada: "PalabraReservada",
    OperadorDosPuntos : "OperadorDosPuntos",
    OperadorPunto : "OperadorPunto",
    NumeroEntero : "NumeroEntero",
    NumeroFlotante : "NumeroFlotante",
    OperadorIncremento : "OperadorIncremento",
    OperadorDecremento: "OperadorDecremento",
    OperadorAritmetico: "OperadorAritmetico",
    OperadorBits: "OperadorBit",
    OperadorLigico: "OperadoLogico",
    OperadorRelacional: "OperadorRelacional",
    OperadorAsignacion: "OperadorAsignacion",
    ParentesisApertura: "ParentesisApertura",
    ParentesisCierre: "ParentesisCierre",
    LlavesApertura: "LlavesApertura",
    LlavesCierre: "LlavesCierre",
    ArregloApertura : "ArregloApertura",
    ArregloCierre : "ArregloCierre",
    Terminal: "Terminal",
    Separador: "Separador",
    ComentarioLinea: "ComentarioLinea",
    ComentarioBloque: "ComentarioBloque",
    Hexadecimal: "Hexadecimal",
    CadenaCaracteres: "CadenaCaracteres",
    Identificador : "Identificador",
    NoReconocido : "NoReconocido",
    OperadoresArreglo : "OperadoresArreglo",
};